name: prod_env
channels:
  - conda-forge  # 改用conda-forge（跨平台兼容性更好）
dependencies:
  - python=3.8.20
  - numpy=1.24.3
  - gdal=3.6.2
  - scipy=1.10.1
  - pip:
    - torch==2.4.1
    - torchvision==0.19.1
    - sanic==21.9.3
    - rasterio==1.3.11